version: "3.1"
services:
  chall-db:
    container_name: chall-db
    image: postgres:13.2-alpine
    restart: always
    env_file:
      - docker/.env
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - 5432:5432
    networks:
      - challenge-network
  chall-app:
    container_name: chall-app
    build:
      context: ""
      dockerfile: docker/Dockerfile
    ports:
      - 8080:8080
    env_file:
      - docker/.env
    image: challenge-app
    networks:
      - challenge-network
    depends_on:
      - chall-db
networks:
  challenge-network:
volumes:
  postgres-data: