package com.duviv.challenge.country.model;

public enum CountriesList {
    BD(new Country("Bangladesh", "", "Bangladesh", Continent.ASIE)),
    BE(new Country("Belgium", "", "Belgique", Continent.EUROPE)),
    BF(new Country("Burkina Faso", "", "Burkina Faso", Continent.AFRIQUE)),
    BG(new Country("Bulgaria", "", "Bulgarie", Continent.EUROPE)),
    BA(new Country("Bosnia and Herzegovina", "", "Bosnie herzegovine", Continent.EUROPE)),
    BB(new Country("Barbados", "", "barbade", Continent.AMERIQUE)),
    BN(new Country("Brunei", "", "Brunei", Continent.ASIE)),
    BO(new Country("Bolivia", "", "Bolivie", Continent.AMERIQUE)),
    BH(new Country("Bahrain", "", "Bahrein", Continent.ASIE)),
    BI(new Country("Burundi", "", "Burundi", Continent.AFRIQUE)),
    BJ(new Country("Benin", "", "Benin", Continent.AFRIQUE)),
    BT(new Country("Bhutan", "", "Bhoutan", Continent.ASIE)),
    JM(new Country("Jamaica", "", "Jamaique", Continent.AMERIQUE)),
    BW(new Country("Botswana", "", "Botswana", Continent.AFRIQUE)),
    WS(new Country("Samoa", "", "Samoa", Continent.OCEANIE)),
    BR(new Country("Brazil", "", "Bresil", Continent.AMERIQUE)),
    BS(new Country("Bahamas", "", "Bahamas", Continent.AMERIQUE)),
    BY(new Country("Belarus", "", "Bielorussie", Continent.EUROPE)),
    BZ(new Country("Belize", "", "Belize", Continent.AMERIQUE)),
    RU(new Country("Russia", "", "Russie", Continent.EUROPE)),
    RW(new Country("Rwanda", "", "Rwanda", Continent.AFRIQUE)),
    RS(new Country("Serbia", "", "Serbie", Continent.EUROPE)),
    TL(new Country("East Timor", "", "Timor Oriental", Continent.ASIE)),
    TM(new Country("Turkmenistan", "", "Turkmenistan", Continent.ASIE)),
    TJ(new Country("Tajikistan", "", "Tadjikistan", Continent.ASIE)),
    RO(new Country("Romania", "", "Roumanie", Continent.EUROPE)),
    GW(new Country("Guinea - Bissau", "", "Guinée-bissau", Continent.AFRIQUE)),
    GT(new Country("Guatemala", "", "Guatemala", Continent.AMERIQUE)),
    GR(new Country("Greece", "", "Grece", Continent.EUROPE)),
    GQ(new Country("Equatorial Guinea", "", "Guinée equatoriale", Continent.AMERIQUE)),
    JP(new Country("Japan", "", "Japon", Continent.ASIE)),
    GY(new Country("Guyana", "", "Guyana", Continent.AFRIQUE)),
    GE(new Country("Georgia", "", "Georgie", Continent.ASIE)),
    GD(new Country("Grenada", "", "Grenade", Continent.AMERIQUE)),
    GB(new Country("United Kingdom", "", "Royaume-uni", Continent.EUROPE)),
    GA(new Country("Gabon", "", "Gabon", Continent.AFRIQUE)),
    SV(new Country("El Salvador", "", "Salvador", Continent.AMERIQUE)),
    GN(new Country("Guinea", "", "Guinée", Continent.AFRIQUE)),
    GM(new Country("Gambia", "", "Gambie", Continent.AFRIQUE)),
    GH(new Country("Ghana", "", "Ghana", Continent.AFRIQUE)),
    OM(new Country("Oman", "", "Oman", Continent.ASIE)),
    TN(new Country("Tunisia", "", "Tunisie", Continent.AFRIQUE)),
    JO(new Country("Jordan", "", "Jordanie", Continent.ASIE)),
    HR(new Country("Croatia", "", "Croatie", Continent.EUROPE)),
    HT(new Country("Haiti", "", "Haiti", Continent.AMERIQUE)),
    HU(new Country("Hungary", "", "Hongrie", Continent.EUROPE)),
    HN(new Country("Honduras", "", "Honduras", Continent.AMERIQUE)),
    VE(new Country("Venezuela", "", "Venezuela", Continent.AMERIQUE)),
    PS(new Country("Palestinian Territory", "", "Palestine", Continent.ASIE)),
    PW(new Country("Palau", "", "Palaos", Continent.OCEANIE)),
    PT(new Country("Portugal", "", "Portugal", Continent.EUROPE)),
    PY(new Country("Paraguay", "", "Paraguay", Continent.AMERIQUE)),
    IQ(new Country("Iraq", "", "Irak", Continent.ASIE)),
    PA(new Country("Panama", "", "Panama", Continent.AMERIQUE)),
    PG(new Country("Papua New Guinea", "", "Papouasie nouvelle guinée", Continent.OCEANIE)),
    PE(new Country("Peru", "", "Perou", Continent.AMERIQUE)),
    PK(new Country("Pakistan", "", "Pakistan", Continent.ASIE)),
    PH(new Country("Philippines", "", "Philippines", Continent.ASIE)),
    PL(new Country("Poland", "", "Pologne", Continent.EUROPE)),
    ZM(new Country("Zambia", "", "Zambie", Continent.AFRIQUE)),
    EE(new Country("Estonia", "", "Estonie", Continent.EUROPE)),
    EG(new Country("Egypt", "", "Egypte", Continent.AFRIQUE)),
    ZA(new Country("South Africa", "", "Afrique du sud", Continent.AFRIQUE)),
    EC(new Country("Ecuador", "", "Equateur", Continent.AMERIQUE)),
    IT(new Country("Italy", "", "Italie", Continent.EUROPE)),
    VN(new Country("Vietnam", "", "Vietnam", Continent.ASIE)),
    SB(new Country("Solomon Islands", "", "Iles salomon", Continent.OCEANIE)),
    ET(new Country("Ethiopia", "", "Ethiopie", Continent.AFRIQUE)),
    SO(new Country("Somalia", "", "Somalie", Continent.AFRIQUE)),
    ZW(new Country("Zimbabwe", "", "Zimbabwe", Continent.AFRIQUE)),
    SA(new Country("Saudi Arabia", "", "Arabie saoudite", Continent.ASIE)),
    ES(new Country("Spain", "", "Espagne", Continent.EUROPE)),
    ER(new Country("Eritrea", "", "Erythrée", Continent.AFRIQUE)),
    ME(new Country("Montenegro", "", "Montenegro", Continent.EUROPE)),
    MD(new Country("Moldova", "", "Moldavie", Continent.EUROPE)),
    MG(new Country("Madagascar", "", "Madagascar", Continent.AFRIQUE)),
    MA(new Country("Morocco", "", "Maroc", Continent.AFRIQUE)),
    MC(new Country("Monaco", "", "Monaco", Continent.EUROPE)),
    UZ(new Country("Uzbekistan", "", "Ouzbekistan", Continent.ASIE)),
    MM(new Country("Myanmar", "", "Birmanie", Continent.ASIE)),
    ML(new Country("Mali", "", "Mali", Continent.AFRIQUE)),
    MN(new Country("Mongolia", "", "Mongolie", Continent.ASIE)),
    MH(new Country("Marshall Islands", "", "Iles marshall", Continent.OCEANIE)),
    MK(new Country("Macedonia", "", "Macedoine du nord", Continent.EUROPE)),
    MU(new Country("Mauritius", "", "Maurice", Continent.AFRIQUE)),
    MT(new Country("Malta", "", "Malte", Continent.EUROPE)),
    MW(new Country("Malawi", "", "Malawi", Continent.AFRIQUE)),
    MV(new Country("Maldives", "", "Maldives", Continent.ASIE)),
    MR(new Country("Mauritania", "", "Mauritanie", Continent.AFRIQUE)),
    UG(new Country("Uganda", "", "Ouganda", Continent.AFRIQUE)),
    TZ(new Country("Tanzania", "", "Tanzanie", Continent.AFRIQUE)),
    MY(new Country("Malaysia", "", "Malaisie", Continent.ASIE)),
    MX(new Country("Mexico", "", "Mexique", Continent.AMERIQUE)),
    IL(new Country("Israel", "", "Israel", Continent.ASIE)),
    FR(new Country("France", "", "France", Continent.EUROPE)),
    FI(new Country("Finland", "", "Finlande", Continent.EUROPE)),
    FJ(new Country("Fiji", "", "Fidji", Continent.OCEANIE)),
    FM(new Country("Micronesia", "", "Micronesie", Continent.OCEANIE)),
    NI(new Country("Nicaragua", "", "Nicaragua", Continent.AMERIQUE)),
    NL(new Country("Netherlands", "", "Pays-bas", Continent.EUROPE)),
    NO(new Country("Norway", "", "Norvege", Continent.EUROPE)),
    NA(new Country("Namibia", "", "Namibie", Continent.AFRIQUE)),
    VU(new Country("Vanuatu", "", "Vanuatu", Continent.OCEANIE)),
    NE(new Country("Niger", "", "Niger", Continent.AFRIQUE)),
    NG(new Country("Nigeria", "", "Nigeria", Continent.AFRIQUE)),
    NZ(new Country("New Zealand", "", "Nouvelle-zelande", Continent.OCEANIE)),
    NP(new Country("Nepal", "", "Nepal", Continent.ASIE)),
    NR(new Country("Nauru", "", "Nauru", Continent.OCEANIE)),
    XK(new Country("Kosovo", "", "Kosovo", Continent.EUROPE)),
    CI(new Country("Ivory Coast", "", "Cote d'ivoire", Continent.AFRIQUE)),
    CH(new Country("Switzerland", "", "Suisse", Continent.EUROPE)),
    CO(new Country("Colombia", "", "Colombie", Continent.AMERIQUE)),
    CN(new Country("China", "", "Chine", Continent.ASIE)),
    CM(new Country("Cameroon", "", "Cameroun", Continent.AFRIQUE)),
    CL(new Country("Chile", "", "Chili", Continent.AMERIQUE)),
    CA(new Country("Canada", "", "Canada", Continent.AMERIQUE)),
    CG(new Country("Republic of the Congo", "", "Congo", Continent.AFRIQUE)),
    CF(new Country("Central African Republic", "", "Republique centrafricaine", Continent.AFRIQUE)),
    CD(new Country("Democratic Republic of the Congo", "", "Republique democratique du congo", Continent.AFRIQUE)),
    CZ(new Country("Czech Republic", "", "Tchequie", Continent.EUROPE)),
    CY(new Country("Cyprus", "", "Chypre", Continent.EUROPE)),
    //CR(new Country("Costa Rica", "Costa rica", Continent.)),
    CU(new Country("Cuba", "", "Cuba", Continent.AMERIQUE)),
    SY(new Country("Syria", "", "Syrie", Continent.ASIE)),
    KG(new Country("Kyrgyzstan", "", "Kirghizistan", Continent.ASIE)),
    KE(new Country("Kenya", "", "Kenya", Continent.AFRIQUE)),
    SS(new Country("South Sudan", "", "Soudan du sud", Continent.AFRIQUE)),
    SR(new Country("Suriname", "", "Suriname", Continent.AMERIQUE)),
    KI(new Country("Kiribati", "", "Kiribati", Continent.OCEANIE)),
    KH(new Country("Cambodia", "", "Cambodge", Continent.ASIE)),
    KM(new Country("Comoros", "", "Comores", Continent.AFRIQUE)),
    ST(new Country("Sao Tome and Principe", "", "Sao tome-et-principe", Continent.AFRIQUE)),
    SK(new Country("Slovakia", "", "Slovaquie", Continent.EUROPE)),
    KR(new Country("South Korea", "", "Corée du sud", Continent.ASIE)),
    SI(new Country("Slovenia", "", "Slovenie", Continent.EUROPE)),
    KP(new Country("North Korea", "", "Corée du nord", Continent.ASIE)),
    KW(new Country("Kuwait", "", "Koweit", Continent.ASIE)),
    SN(new Country("Senegal", "", "Senegal", Continent.AFRIQUE)),
    SM(new Country("San Marino", "", "Saint-marin", Continent.EUROPE)),
    SL(new Country("Sierra Leone", "", "Sierra leone", Continent.AFRIQUE)),
    SC(new Country("Seychelles", "", "Seychelles", Continent.AFRIQUE)),
    KZ(new Country("Kazakhstan", "", "Kazakhstan", Continent.ASIE)),
    SG(new Country("Singapore", "", "Singapour", Continent.ASIE)),
    SE(new Country("Sweden", "", "Suede", Continent.EUROPE)),
    SD(new Country("Sudan", "", "Soudan", Continent.AFRIQUE)),
    DO(new Country("Dominican Republic", "", "Republique dominicaine", Continent.AMERIQUE)),
    DM(new Country("Dominica", "", "Dominique", Continent.AMERIQUE)),
    DJ(new Country("Djibouti", "", "Djibouti", Continent.AFRIQUE)),
    DK(new Country("Denmark", "", "Danemark", Continent.EUROPE)),
    DE(new Country("Germany", "", "Allemagne", Continent.EUROPE)),
    YE(new Country("Yemen", "", "Yemen", Continent.ASIE)),
    DZ(new Country("Algeria", "", "Algerie", Continent.AFRIQUE)),
    US(new Country("United States", "", "Etats-unis", Continent.AMERIQUE)),
    UY(new Country("Uruguay", "", "Uruguay", Continent.AMERIQUE)),
    LB(new Country("Lebanon", "", "Liban", Continent.ASIE)),
    LC(new Country("Saint Lucia", "", "Sainte-lucie", Continent.AMERIQUE)),
    LA(new Country("Laos", "", "Laos", Continent.OCEANIE)),
    TV(new Country("Tuvalu", "", "Tuvalu", Continent.OCEANIE)),
    TT(new Country("Trinidad and Tobago", "", "Trinite-et-tobago", Continent.AMERIQUE)),
    TR(new Country("Turkey", "", "Turquie", Continent.ASIE)),
    LK(new Country("Sri Lanka", "", "Sri lanka", Continent.ASIE)),
    LI(new Country("Liechtenstein", "", "Liechtenstein", Continent.EUROPE)),
    LV(new Country("Latvia", "", "Lettonie", Continent.EUROPE)),
    TO(new Country("Tonga", "", "Tonga", Continent.AFRIQUE)),
    LT(new Country("Lithuania", "", "Lituanie", Continent.EUROPE)),
    LU(new Country("Luxembourg", "", "Luxembourg", Continent.EUROPE)),
    LR(new Country("Liberia", "", "Liberia", Continent.AFRIQUE)),
    LS(new Country("Lesotho", "", "Lesotho", Continent.AFRIQUE)),
    TH(new Country("Thailand", "", "Thailande", Continent.ASIE)),
    TG(new Country("Togo", "", "Togo", Continent.AFRIQUE)),
    TD(new Country("Chad", "", "Tchad", Continent.AFRIQUE)),
    LY(new Country("Libya", "", "Libye", Continent.AFRIQUE)),
    VA(new Country("Vatican", "", "Vatican", Continent.EUROPE)),
    VC(new Country("Saint Vincent and the Grenadines", "", "Saint-vincent-et-les-grendines", Continent.AMERIQUE)),
    AE(new Country("United Arab Emirates", "", "Emirats arabes unis", Continent.ASIE)),
    AD(new Country("Andorra", "", "Andorre", Continent.EUROPE)),
    AG(new Country("Antigua and Barbuda", "", "Antigua-et-barbuda", Continent.AMERIQUE)),
    AF(new Country("Afghanistan", "", "Afghanistan", Continent.ASIE)),
    IS(new Country("Iceland", "", "Islande", Continent.EUROPE)),
    IR(new Country("Iran", "", "Iran", Continent.ASIE)),
    AM(new Country("Armenia", "", "Armenie", Continent.ASIE)),
    AL(new Country("Albania", "", "Albanie", Continent.EUROPE)),
    AO(new Country("Angola", "", "Angola", Continent.AFRIQUE)),
    AS(new Country("American Samoa", "", "Samoa", Continent.OCEANIE)),
    AR(new Country("Argentina", "", "Argentine", Continent.AMERIQUE)),
    AU(new Country("Australia", "", "Australie", Continent.OCEANIE)),
    AT(new Country("Austria", "", "Autrique", Continent.EUROPE)),
    IN(new Country("India", "", "Inde", Continent.ASIE)),
    AZ(new Country("Azerbaijan", "", "Azerbaidjan", Continent.ASIE)),
    IE(new Country("Ireland", "", "Irlande", Continent.EUROPE)),
    ID(new Country("Indonesia", "", "Indonesie", Continent.ASIE)),
    UA(new Country("Ukraine", "", "Ukraine", Continent.EUROPE)),
    QA(new Country("Qatar", "", "Qatar", Continent.ASIE)),
    MZ(new Country("Mozambique", "", "Mozambique", Continent.AFRIQUE));
    //WF(new Country("Wallis and Futuna", Continent.)),
    //BL(new Country("Saint Barthelemy", Continent.)),
    //BM(new Country("Bermuda", Continent.)),
    //BV(new Country("Bouvet Island", Continent.)),
    //BQ(new Country("Bonaire, Saint Eustatius and Saba", Continent.)),
    //JE(new Country("Jersey", Continent.)),
    //RE(new Country("Reunion","", Continent.)),
    //TK(new Country("Tokelau","", Continent.)),
    //GU(new Country("Guam","", Continent.)),
    //GS(new Country("South Georgia and the South Sandwich Islands","", Continent.)),
    //GP(new Country("Guadeloupe","Guadeloupe", Continent.)),
    //GG(new Country("Guernsey","", Continent.)),
    //GF(new Country("French Guiana","Guyane", Continent.)),
    //GL(new Country("Greenland","Groenland", Continent.)),
    //GI(new Country("Gibraltar","", Continent.)),
    //HK(new Country("Hong Kong","", Continent.)),
    //HM(new Country("Heard Island and McDonald Islands","", Continent.)),
    //PR(new Country("Puerto Rico","Porto rico", Continent.)),
    //SJ(new Country("Svalbard and Jan Mayen","", Continent.)),
    //PF(new Country("French Polynesia","Polynesie française", Continent.)),
    //PN(new Country("Pitcairn","", Continent.)),
    //PM(new Country("Saint Pierre and Miquelon","", Continent.)),
    //EH(new Country("Western Sahara","", Continent.)),
    //MF(new Country("Saint Martin","", Continent.)),
    //MO(new Country("Macao","", Continent.)),
    //MQ(new Country("Martinique","Martinique", Continent.)),
    //MP(new Country("Northern Mariana Islands","", Continent.)),
    //MS(new Country("Montserrat","", Continent.)),
    //IM(new Country("Isle of Man","", Continent.)),
    //IO(new Country("British Indian Ocean Territory","", Continent.)),
    //SH(new Country("Saint Helena","", Continent.)),
    //FK(new Country("Falkland Islands","", Continent.)),
    //FO(new Country("Faroe Islands","", Continent.)),
    //NC(new Country("New Caledonia","Nouvelle caledonie", Continent.)),
    //NF(new Country("Norfolk Island","", Continent.)),
    //NU(new Country("Niue","", Continent.)),
    //CK(new Country("Cook Islands","", Continent.)),
    //CC(new Country("Cocos Islands","", Continent.)),
    //CX(new Country("Christmas Island","", Continent.)),
    //CW(new Country("Curacao","", Continent.)),
    //CV(new Country("Cape Verde","Cap-vert", Continent.)),
    //SZ(new Country("Swaziland","", Continent.)),
    //SX(new Country("Sint Maarten","", Continent.)),
    //KN(new Country("Saint Kitts and Nevis","", Continent.)),
    //KY(new Country("Cayman Islands","", Continent.)),
    //VG(new Country("British Virgin Islands","", Continent.)),
    //YT(new Country("Mayotte","Mayotte", Continent.)),
    //UM(new Country("United States Minor Outlying Islands","", Continent.)),
    //TW(new Country("Taiwan","Taiwan", Continent.)),
    //TF(new Country("French Southern Territories","", Continent.)),
    //TC(new Country("Turks and Caicos Islands","", Continent).)
    //AI(new Country("Anguilla","", Continent.)),
    //VI(new Country("U.S.Virgin Islands","", Continent.)),
    //AQ(new Country("Antarctica","Antartique", Continent.)),
    //AW(new Country("Aruba","", Continent.)),
    //AX(new Country("Aland Islands","", Continent.)),

    private final Country country;

    CountriesList(Country country) {
        this.country = country;
    }

    public Country getCountry() {
        return country;
    }
}
